In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

DATA_DIR = Path("data")

raw = pd.read_pickle(
    DATA_DIR / "raw/routerbench_0shot.pkl"
)

print("Type:", type(raw))
print("Shape:", raw.shape)

display(raw.head())

Type: <class 'pandas.DataFrame'>
Shape: (36497, 37)

,sample_id,prompt,eval_name,WizardLM/WizardLM-13B-V1.2,claude-instant-v1,claude-v1,claude-v2,gpt-3.5-turbo-1106,gpt-4-1106-preview,meta/code-llama-instruct-34b-chat,...,claude-v1|total_cost,claude-v2|total_cost,gpt-4-1106-preview|total_cost,meta/llama-2-70b-chat|total_cost,mistralai/mixtral-8x7b-chat|total_cost,zero-one-ai/Yi-34B-Chat|total_cost,WizardLM/WizardLM-13B-V1.2|total_cost,meta/code-llama-instruct-34b-chat|total_cost,mistralai/mistral-7b-chat|total_cost,oracle_model_to_route_to
0,Chinese_character_riddles.dev.0,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.004904,0.006488,0.00973,0.000266,0.000166,0.000250,0.000103,0.000236,0.000062,no_model_correct
1,Chinese_character_riddles.dev.1,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.003096,0.004704,0.01077,0.000257,0.000227,0.000226,0.000073,0.000128,0.000050,no_model_correct
2,Chinese_character_riddles.dev.10,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002480,0.003728,0.01105,0.000232,0.000215,0.000215,0.000138,0.000150,0.000051,zero-one-ai/Yi-34B-Chat
3,Chinese_character_riddles.dev.11,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.003088,0.004960,0.00908,0.000287,0.000117,0.000318,0.000104,0.000315,0.000045,zero-one-ai/Yi-34B-Chat
4,Chinese_character_riddles.dev.12,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.002272,0.004912,0.01322,0.000254,0.000097,0.000210,0.000112,0.000190,0.000039,no_model_correct

In [2]:
for i, col in enumerate(raw.columns):
    print(i, col)

0 sample_id
1 prompt
2 eval_name
3 WizardLM/WizardLM-13B-V1.2
4 claude-instant-v1
5 claude-v1
6 claude-v2
7 gpt-3.5-turbo-1106
8 gpt-4-1106-preview
9 meta/code-llama-instruct-34b-chat
10 meta/llama-2-70b-chat
11 mistralai/mistral-7b-chat
12 mistralai/mixtral-8x7b-chat
13 zero-one-ai/Yi-34B-Chat
14 gpt-3.5-turbo-1106|model_response
15 claude-instant-v1|model_response
16 claude-v1|model_response
17 claude-v2|model_response
18 gpt-4-1106-preview|model_response
19 meta/llama-2-70b-chat|model_response
20 mistralai/mixtral-8x7b-chat|model_response
21 zero-one-ai/Yi-34B-Chat|model_response
22 WizardLM/WizardLM-13B-V1.2|model_response
23 meta/code-llama-instruct-34b-chat|model_response
24 mistralai/mistral-7b-chat|model_response
25 gpt-3.5-turbo-1106|total_cost
26 claude-instant-v1|total_cost
27 claude-v1|total_cost
28 claude-v2|total_cost
29 gpt-4-1106-preview|total_cost
30 meta/llama-2-70b-chat|total_cost
31 mistralai/mixtral-8x7b-chat|total_cost
32 zero-one-ai/Yi-34B-Chat|total_cost
33 WizardLM/WizardLM-13B-V1.2|total_cost
34 meta/code-llama-instruct-34b-chat|total_cost
35 mistralai/mistral-7b-chat|total_cost
36 oracle_model_to_route_to

In [3]:
raw.info()

display(
    raw.isna().sum().sort_values(ascending=False)
)

<class 'pandas.DataFrame'>
RangeIndex: 36497 entries, 0 to 36496
Data columns (total 37 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   sample_id                                         36497 non-null  object
 1   prompt                                            36497 non-null  object
 2   eval_name                                         36497 non-null  object
 3   WizardLM/WizardLM-13B-V1.2                        36497 non-null  object
 4   claude-instant-v1                                 36497 non-null  object
 5   claude-v1                                         36497 non-null  object
 6   claude-v2                                         36497 non-null  object
 7   gpt-3.5-turbo-1106                                36497 non-null  object
 8   gpt-4-1106-preview                                36497 non-null  object
 9   meta/code-llama-instruct-34b-chat                 36497 non-null  object
 10  meta/llama-2-70b-chat                             36497 non-null  object
 11  mistralai/mistral-7b-chat                         36497 non-null  object
 12  mistralai/mixtral-8x7b-chat                       36497 non-null  object
 13  zero-one-ai/Yi-34B-Chat                           36497 non-null  object
 14  gpt-3.5-turbo-1106|model_response                 36497 non-null  object
 15  claude-instant-v1|model_response                  36497 non-null  object
 16  claude-v1|model_response                          36497 non-null  object
 17  claude-v2|model_response                          36497 non-null  object
 18  gpt-4-1106-preview|model_response                 36497 non-null  object
 19  meta/llama-2-70b-chat|model_response              36497 non-null  object
 20  mistralai/mixtral-8x7b-chat|model_response        36497 non-null  object
 21  zero-one-ai/Yi-34B-Chat|model_response            36497 non-null  object
 22  WizardLM/WizardLM-13B-V1.2|model_response         36497 non-null  object
 23  meta/code-llama-instruct-34b-chat|model_response  36497 non-null  object
 24  mistralai/mistral-7b-chat|model_response          36497 non-null  object
 25  gpt-3.5-turbo-1106|total_cost                     36497 non-null  float64
 26  claude-instant-v1|total_cost                      36497 non-null  float64
 27  claude-v1|total_cost                              36497 non-null  float64
 28  claude-v2|total_cost                              36497 non-null  float64
 29  gpt-4-1106-preview|total_cost                     36497 non-null  float64
 30  meta/llama-2-70b-chat|total_cost                  36497 non-null  float64
 31  mistralai/mixtral-8x7b-chat|total_cost            36497 non-null  float64
 32  zero-one-ai/Yi-34B-Chat|total_cost                36497 non-null  float64
 33  WizardLM/WizardLM-13B-V1.2|total_cost             36497 non-null  float64
 34  meta/code-llama-instruct-34b-chat|total_cost      36497 non-null  float64
 35  mistralai/mistral-7b-chat|total_cost              36497 non-null  float64
 36  oracle_model_to_route_to                          36497 non-null  object
dtypes: float64(11), object(26)
memory usage: 10.3+ MB

sample_id                                           0
meta/llama-2-70b-chat|model_response                0
zero-one-ai/Yi-34B-Chat|model_response              0
WizardLM/WizardLM-13B-V1.2|model_response           0
meta/code-llama-instruct-34b-chat|model_response    0
mistralai/mistral-7b-chat|model_response            0
gpt-3.5-turbo-1106|total_cost                       0
claude-instant-v1|total_cost                        0
claude-v1|total_cost                                0
claude-v2|total_cost                                0
gpt-4-1106-preview|total_cost                       0
meta/llama-2-70b-chat|total_cost                    0
mistralai/mixtral-8x7b-chat|total_cost              0
zero-one-ai/Yi-34B-Chat|total_cost                  0
WizardLM/WizardLM-13B-V1.2|total_cost               0
meta/code-llama-instruct-34b-chat|total_cost        0
mistralai/mistral-7b-chat|total_cost                0
mistralai/mixtral-8x7b-chat|model_response          0
gpt-4-1106-preview|model_response                   0
prompt                                              0
claude-v2|model_response                            0
eval_name                                           0
WizardLM/WizardLM-13B-V1.2                          0
claude-instant-v1                                   0
claude-v1                                           0
claude-v2                                           0
gpt-3.5-turbo-1106                                  0
gpt-4-1106-preview                                  0
meta/code-llama-instruct-34b-chat                   0
meta/llama-2-70b-chat                               0
mistralai/mistral-7b-chat                           0
mistralai/mixtral-8x7b-chat                         0
zero-one-ai/Yi-34B-Chat                             0
gpt-3.5-turbo-1106|model_response                   0
claude-instant-v1|model_response                    0
claude-v1|model_response                            0
oracle_model_to_route_to                            0
dtype: int64

In [4]:
display(
    raw["eval_name"].value_counts()
)

eval_name
hellaswag                    10042
grade-school-math             7450
mmlu-professional-law         1534
arc-challenge                 1470
winogrande                    1267
                             ...
chinese-remainder-theorem       15
chinese_chu_ci                  15
chinese_idioms                  15
chinese_poem                    15
test-match                       3
Name: count, Length: 86, dtype: int64

In [5]:
processed_dir = DATA_DIR / "processed"
tfidf_dir = processed_dir / "char_tfidf_50k"

questions = pd.read_pickle(
    tfidf_dir / "train_questions.pkl"
)

print("Shape:", questions.shape)
print("Columns:", questions.columns.tolist())

display(questions.head())

Shape: (21900, 6)
Columns: ['sample_id', 'prompt', 'eval_name', 'question_text', 'question_group', 'split']

,sample_id,prompt,eval_name,question_text,question_group,split
0,Chinese_character_riddles.dev.0,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)。首...,0,train
3,Chinese_character_riddles.dev.11,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)。首...,3,train
4,Chinese_character_riddles.dev.12,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)。首...,4,train
5,Chinese_character_riddles.dev.13,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)。首...,5,train
6,Chinese_character_riddles.dev.14,['猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)...,Chinese_character_riddles,猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)。首...,6,train

In [6]:
print(questions.iloc[0]["question_text"])

猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)。首先提供你的推理，然后提供用英文方括号括[]起来的最终答案。

古字刚分开，豆字挤进来，你先别生气，看后笑开怀。

In [7]:
print(questions.iloc[0]["eval_name"])

Chinese_character_riddles

In [8]:
scores = pd.read_pickle(
    tfidf_dir / "train_scores.pkl"
)

costs = pd.read_pickle(
    tfidf_dir / "train_costs.pkl"
)

print("Scores shape:", scores.shape)
print("Costs shape:", costs.shape)

display(scores.head())
display(costs.head())

Scores shape: (21900, 11)
Costs shape: (21900, 11)

,WizardLM/WizardLM-13B-V1.2,claude-instant-v1,claude-v1,claude-v2,gpt-3.5-turbo-1106,gpt-4-1106-preview,meta/code-llama-instruct-34b-chat,meta/llama-2-70b-chat,mistralai/mistral-7b-chat,mistralai/mixtral-8x7b-chat,zero-one-ai/Yi-34B-Chat
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,WizardLM/WizardLM-13B-V1.2,claude-instant-v1,claude-v1,claude-v2,gpt-3.5-turbo-1106,gpt-4-1106-preview,meta/code-llama-instruct-34b-chat,meta/llama-2-70b-chat,mistralai/mistral-7b-chat,mistralai/mixtral-8x7b-chat,zero-one-ai/Yi-34B-Chat
0,0.000103,0.000099,0.004904,0.006488,0.000527,0.00973,0.000236,0.000266,0.000062,0.000166,0.000250
3,0.000104,0.000093,0.003088,0.004960,0.000243,0.00908,0.000315,0.000287,0.000045,0.000117,0.000318
4,0.000112,0.000090,0.002272,0.004912,0.000227,0.01322,0.000190,0.000254,0.000039,0.000097,0.000210
5,0.000076,0.000134,0.005640,0.005976,0.000196,0.00837,0.000150,0.000247,0.000022,0.000248,0.000210
6,0.000049,0.000090,0.002600,0.002336,0.000303,0.01069,0.000294,0.000271,0.000035,0.000099,0.000258

In [9]:
print(scores.columns.tolist())

['WizardLM/WizardLM-13B-V1.2', 'claude-instant-v1', 'claude-v1', 'claude-v2', 'gpt-3.5-turbo-1106', 'gpt-4-1106-preview', 'meta/code-llama-instruct-34b-chat', 'meta/llama-2-70b-chat', 'mistralai/mistral-7b-chat', 'mistralai/mixtral-8x7b-chat', 'zero-one-ai/Yi-34B-Chat']

In [10]:
summary = pd.DataFrame({
    "Mean score": scores.mean(),
    "Mean cost": costs.mean(),
    "Cost std": costs.std(),
})

display(summary)

                                  Mean score  Mean cost  Cost std
WizardLM/WizardLM-13B-V1.2          0.432913   0.000073  0.000053
claude-instant-v1                   0.596991   0.000233  0.000210
claude-v1                           0.628566   0.002144  0.001805
claude-v2                           0.631646   0.002420  0.002200
gpt-3.5-turbo-1106                  0.618126   0.000243  0.000181
gpt-4-1106-preview                  0.779986   0.003298  0.003442
meta/code-llama-instruct-34b-chat   0.201646   0.000172  0.000111
meta/llama-2-70b-chat               0.325543   0.000202  0.000133
mistralai/mistral-7b-chat           0.307167   0.000046  0.000038
mistralai/mixtral-8x7b-chat         0.545813   0.000135  0.000088
zero-one-ai/Yi-34B-Chat             0.648537   0.000186  0.000133

In [11]:
from scipy.sparse import load_npz

X_tfidf = load_npz(tfidf_dir / "X_train.npz")

print("Type:", type(X_tfidf))
print("Shape:", X_tfidf.shape)
print("Nonzero entries:", X_tfidf.nnz)

Type: <class 'scipy.sparse._csr.csr_matrix'>
Shape: (21900, 50001)
Nonzero entries: 25345680

In [12]:
import joblib

preprocessing = joblib.load(
    tfidf_dir / "preprocessing.joblib"
)

vectorizer = preprocessing["tfidf_vectorizer"]

print("Number of TF-IDF features:",
      len(vectorizer.get_feature_names_out()))

print("First 20:")
print(vectorizer.get_feature_names_out()[:20])

Number of TF-IDF features: 50000
First 20:
['\n"' '\n"A' '\n"I' '\n"I ' '\n"T' '\n"Th' '\n"W' '\n"We' '\n"Wh' '\n('
 '\n-' '\n--' '\n---' '\n1' '\n2' '\nA' '\nA ' '\nA)' '\nA) ' '\nAl']

In [13]:
e5_dir = processed_dir / "multilingual_e5_small_chunk480"

X_e5 = np.load(e5_dir / "X_train_e5.npy")

X_e5_basic = np.load(
    e5_dir / "X_train_e5_features.npy"
)

X_e5_full = np.load(
    e5_dir / "X_train_e5_full_features.npy"
)

print("E5 only:", X_e5.shape)
print("E5 + length:", X_e5_basic.shape)
print("E5 full:", X_e5_full.shape)

E5 only: (21900, 384)
E5 + length: (21900, 385)
E5 full: (21900, 388)

In [14]:
print(X_e5_full[0])

[ 9.14106891e-02 -2.12806184e-02 -5.69672734e-02 -3.42570357e-02
  9.88215581e-02 -2.05737408e-02  9.83818062e-03  3.76888700e-02
  7.10394755e-02 -2.47906893e-02  5.00152186e-02 -2.06122398e-02
  1.09846942e-01  2.63303667e-02 -5.80159575e-02  2.99583133e-02
  6.05744608e-02 -5.69261536e-02 -2.40688697e-02 -6.17754683e-02
  3.03263254e-02 -1.34096844e-02 -3.20948213e-02  6.34077713e-02
  5.49232773e-02  4.32637967e-02 -3.37255225e-02  6.28118142e-02
  4.64658253e-02 -3.34529504e-02 -2.50538774e-02 -7.15354877e-03
  6.57262355e-02 -4.34429571e-02  6.74041137e-02  2.92017087e-02
 -7.24269003e-02 -3.06218956e-02  4.28180993e-02 -5.93902282e-02
 -4.99055348e-02  9.81154852e-03  6.06811382e-02  8.13420638e-02
  7.39719346e-02  9.37632546e-02 -6.22367524e-02  5.49428388e-02
 -7.84370154e-02 -1.12938480e-02 -4.04048152e-02  7.19228685e-02
 -3.89282219e-03  3.41804661e-02 -3.82855511e-03 -6.36865869e-02
 -3.69252488e-02 -1.00651793e-01 -1.02488868e-01  9.33999643e-02
  8.63550678e-02  6.48392132e-04 -2.29663737e-02  2.44098771e-02
  7.04675242e-02  3.54632735e-02  4.59845327e-02  1.78283285e-02
 -3.07661034e-02 -7.75353657e-03 -2.25413498e-02  7.07059875e-02
  1.36037469e-02 -5.55947945e-02  1.66520998e-02  1.41732581e-02
  2.97467131e-02 -1.89157426e-02  6.22190200e-02 -4.59748209e-02
 -9.34334695e-02 -3.49556394e-02 -3.56042944e-02  3.28375101e-02
 -8.15433934e-02  4.95224260e-02  3.12498435e-02 -4.52934727e-02
  7.00783059e-02 -2.04216167e-02  7.35745355e-02  9.16315615e-02
 -4.41651717e-02 -5.83211221e-02 -7.93273598e-02 -8.63759294e-02
 -5.73781766e-02  6.82580695e-02  9.32645127e-02  9.15502943e-03
  8.69975016e-02 -2.45893151e-02  2.50614178e-03 -8.88748765e-02
 -3.67173180e-02  6.04397729e-02  3.03614326e-02 -5.65743074e-02
  6.40603304e-02 -5.87997511e-02 -2.88936310e-02  5.15681468e-02
  8.01923405e-03  6.34101927e-02 -6.61791414e-02 -9.34573356e-03
 -2.94107832e-02 -8.17005336e-02  3.30579989e-02 -6.69111013e-02
  3.72426659e-02 -3.72581556e-02 -4.24068235e-02  1.23447317e-04
 -8.20850357e-02 -3.53415720e-02  2.04787347e-02  4.88499850e-02
 -2.19830647e-02 -2.71923710e-02  1.43476250e-02  6.60856739e-02
 -1.90578476e-02  4.64069583e-02 -3.37360427e-03  1.07502893e-01
 -2.59850416e-02  4.49697226e-02  7.98912160e-03 -7.15278164e-02
 -3.03661842e-02  4.04495113e-02 -1.49054658e-02  5.07755429e-02
  5.51657602e-02  5.77475317e-02  4.76452187e-02 -5.83976414e-03
  7.12298974e-02 -5.96740730e-02  3.03172995e-03 -1.46901049e-02
  7.60986507e-02  4.31530364e-02  4.42263782e-02 -6.47370964e-02
 -3.86082679e-02 -2.54574921e-02  3.64531530e-03  4.70572002e-02
 -8.44388157e-02 -7.88963437e-02 -6.40154406e-02 -4.56034355e-02
 -7.27143437e-02 -7.19351619e-02  4.69002277e-02  4.88041528e-02
 -4.90843318e-02 -4.13395055e-02 -1.26656080e-02  1.49127776e-02
 -3.75598893e-02  1.89228915e-02  1.37782318e-03  3.73648256e-02
 -5.20788543e-02  3.82357165e-02  8.09980556e-02  3.82510573e-02
  1.18514430e-02 -4.07560281e-02 -5.41093834e-02 -3.25807184e-02
 -5.66415638e-02  8.18615314e-04 -6.19480275e-02  3.96564454e-02
  6.44121915e-02  8.87126010e-03 -3.88070708e-03  6.55533075e-02
 -2.27848738e-02 -5.86440228e-02 -3.52308936e-02 -6.48962054e-03
 -3.94676812e-02  2.67941356e-02  3.68028879e-02  6.20490983e-02
 -3.38888466e-02 -3.50861885e-02  4.20821607e-02  4.91262041e-03
  4.19220105e-02 -6.65041804e-03 -5.98244183e-02  7.52549572e-03
 -4.10757735e-02  3.53832692e-02  3.46918292e-02 -9.73497480e-02
 -1.12934671e-01  4.86988910e-02 -9.08831730e-02 -3.89854722e-02
 -1.93211492e-02  7.04860464e-02 -5.24731427e-02  4.05245796e-02
  4.54338156e-02 -2.31685047e-03  5.20970337e-02 -7.03707263e-02
 -4.21284176e-02  4.97846529e-02  7.12039769e-02 -7.26758763e-02
 -4.41803671e-02 -1.20210107e-02 -5.27429059e-02 -3.56058106e-02
 -4.48618196e-02 -6.83490783e-02 -2.82758996e-02 -8.75921175e-02
 -2.20567230e-02  1.82233714e-02  7.47172311e-02 -5.31346276e-02
 -6.97210478e-03 -5.68175986e-02 -4.81544295e-03 -6.58691525e-02
  2.89556291e-02 -7.84785897e-02 -3.63264792e-02  5.34479469e-02
 -1.74228437e-02  5.91200739e-02  2.38347147e-02 -6.14449829e-02
 -3.00731938e-02 -8.51770565e-02 -3.18480581e-02  3.07563506e-02
  7.00272620e-02  1.06236033e-01 -5.01234718e-02  2.73652691e-02
  2.96942685e-02 -3.99411917e-02  8.60480219e-02  7.37314299e-02
  5.31924292e-02  5.04198670e-02 -5.82783446e-02 -1.99551992e-02
 -5.48061840e-02 -5.92516223e-03 -2.02249177e-02  2.83871796e-02
  6.62338436e-02 -6.21900596e-02 -4.11012918e-02 -3.60752270e-02
  6.26207888e-02  7.07252920e-02 -3.27665843e-02 -4.53703627e-02
  7.42075592e-02 -3.68284527e-03  4.17469721e-03  2.94097792e-02
  6.23733699e-02  7.20808888e-03 -2.79517658e-02  3.77247334e-02
 -1.01766400e-02  3.18991169e-02 -1.21188844e-02 -6.56534582e-02
  5.46571128e-02 -2.18514167e-02  8.68972763e-02  4.10716496e-02
 -2.11670920e-02  6.74853846e-02 -7.35974312e-02  3.63350771e-02
 -2.86214445e-02 -4.81818132e-02  5.91406263e-02 -8.37280601e-03
 -1.01896428e-01  2.74045784e-02  9.81676020e-03  2.56646927e-02
  9.79937986e-03  2.41944436e-02  7.80895799e-02  5.30618057e-02
 -1.84273496e-02 -4.81902063e-02  2.79795378e-02  1.02865910e-02
 -9.23954044e-03  1.31822005e-02 -8.51342753e-02 -3.81769724e-02
 -3.64417545e-02 -6.03503995e-02 -4.11068052e-02 -7.40589574e-02
  2.37283856e-02  3.52467708e-02 -4.91796657e-02 -3.96206267e-02
  7.09188133e-02  3.88994701e-02 -1.62839983e-03 -3.60426418e-02
 -4.10825424e-02  1.16129071e-02 -3.59855145e-02 -1.86523926e-02
 -2.51592640e-02  7.23038465e-02 -6.75294101e-02 -6.71225786e-02
  2.58915909e-02  5.72598539e-02 -4.84924726e-02  7.19924346e-02
 -3.79004478e-02 -6.88465834e-02  9.78612714e-03 -1.20148240e-02
 -3.35771823e-03  4.58349772e-02  4.34977561e-02 -9.30390432e-02
  3.45342234e-02  8.67156759e-02 -5.20716831e-02  3.23721543e-02
 -6.58481866e-02 -4.69515957e-02  7.19749779e-02  4.61097993e-02
 -5.62773868e-02 -4.52894084e-02  6.33319542e-02  5.83937652e-02
  1.70154404e-02 -3.63664306e-03  1.33333430e-02 -5.90738980e-03
  4.18212079e-02 -6.50516078e-02  6.94093481e-02  2.80377548e-02
 -7.38680810e-02  1.77501738e-02 -2.73754559e-02 -2.98743434e-02
 -8.31466392e-02  3.32219228e-02 -3.48210931e-02 -2.84259859e-02
  1.40600689e-02  7.69167915e-02  6.73976541e-02  8.35411996e-02
 -1.53700411e+00 -1.62652814e+00 -6.61991835e-01  0.00000000e+00]

In [15]:
print(questions.iloc[0]["question_text"])

猜字谜，根据我给的描述猜出一个字(请从汉字的字形、发音、意义以及字的拆分组合等角度考虑)。首先提供你的推理，然后提供用英文方括号括[]起来的最终答案。

古字刚分开，豆字挤进来，你先别生气，看后笑开怀。

In [16]:
import pandas as pd
import numpy as np
from scipy.sparse import load_npz

for split in ["train", "calibration", "validation", "test"]:

    q = pd.read_pickle(tfidf_dir / f"{split}_questions.pkl")
    s = pd.read_pickle(tfidf_dir / f"{split}_scores.pkl")
    c = pd.read_pickle(tfidf_dir / f"{split}_costs.pkl")

    x_tfidf = load_npz(tfidf_dir / f"X_{split}.npz")
    x_e5 = np.load(e5_dir / f"X_{split}_e5_full_features.npy")

    print(f"\n===== {split.upper()} =====")
    print("Questions:", q.shape)
    print("Scores:   ", s.shape)
    print("Costs:    ", c.shape)
    print("TF-IDF:   ", x_tfidf.shape)
    print("E5:       ", x_e5.shape)

===== TRAIN =====
Questions: (21900, 6)
Scores:    (21900, 11)
Costs:     (21900, 11)
TF-IDF:    (21900, 50001)
E5:        (21900, 388)

===== CALIBRATION =====
Questions: (3648, 6)
Scores:    (3648, 11)
Costs:     (3648, 11)
TF-IDF:    (3648, 50001)
E5:        (3648, 388)

===== VALIDATION =====
Questions: (3649, 6)
Scores:    (3649, 11)
Costs:     (3649, 11)
TF-IDF:    (3649, 50001)
E5:        (3649, 388)

===== TEST =====
Questions: (7300, 6)
Scores:    (7300, 11)
Costs:     (7300, 11)
TF-IDF:    (7300, 50001)
E5:        (7300, 388)